// <auto-generated />
using System;
using EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240918015947_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entity.Config.Config_file_first_kind", b =>
                {
                    b.Property<int>("Ffk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ffk_id"));

                    b.Property<string>("First_kind_id")
                        .HasMaxLength(2)
                        .HasColumnType("char()");

                    b.Property<string>("First_kind_name")
                        .HasMaxLength(60)
                        .HasColumnType("varchar()");

                    b.Property<string>("First_kind_salary_id")
                        .HasColumnType("text");

                    b.Property<string>("First_kind_sale_id")
                        .HasColumnType("text");

                    b.HasKey("Ffk_id");

                    b.ToTable("Config_file_first_kind", (string)null);

                    b.HasData(
                        new
                        {
                            Ffkid = 1,
                            Firstkindid = "01",
                            Firstkindname = "集团",
                            Firstkindsalaryid = "1",
                            Firstkindsaleid = "1"
                        });
                });

            modelBuilder.Entity("Domain.Entity.Config.Config_file_second_kind", b =>
                {
                    b.Property<int>("Fsk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Fsk_id"));

                    b.Property<string>("First_kind_id")
                        .HasMaxLength(2)
                        .HasColumnType("char()");

                    b.Property<string>("First_kind_name")
                        .HasMaxLength(60)
                        .HasColumnType("varchar()");

                    b.Property<string>("Second_kind_id")
                        .HasMaxLength(2)
                        .HasColumnType("char()");

                    b.Property<string>("Second_kind_name")
                        .HasMaxLength(60)
                        .HasColumnType("varchar()");

                    b.Property<string>("Second_salary_id")
                        .HasColumnType("text");

                    b.Property<string>("Second_sale_id")
                        .HasColumnType("text");

                    b.HasKey("Fsk_id");

                    b.ToTable("Config_file_second_kind", (string)null);

                    b.HasData(
                        new
                        {
                            Fskid = 1,
                            Firstkindid = "01",
                            Firstkindname = "集团",
                            Secondkindid = "01",
                            Secondkindname = "软件公司",
                            Secondsalaryid = "1",
                            Secondsaleid = "1"
                        });
                });

            modelBuilder.Entity("Domain.Entity.Config.Config_file_third_kind", b =>
                {
                    b.Property<int>("Ftk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ftk_id"));

                    b.Property<string>("First_kind_id")
                        .HasMaxLength(2)
                        .HasColumnType("char()");

                    b.Property<string>("First_kind_name")
                        .HasMaxLength(60)
                        .HasColumnType("varchar()");

                    b.Property<string>("Second_kind_id")
                        .HasMaxLength(2)
                        .HasColumnType("char()");

                    b.Property<string>("Second_kind_name")
                        .HasMaxLength(60)
                        .HasColumnType("varchar()");

                    b.Property<string>("Third_kind_id")
                        .HasMaxLength(2)
                        .HasColumnType("char()");

                    b.Property<string>("Third_kind_is_retail")
                        .HasMaxLength(2)
                        .HasColumnType("char()");

                    b.Property<string>("Third_kind_name")
                        .HasMaxLength(60)
                        .HasColumnType("varchar()");

                    b.Property<string>("Third_kind_sale_id")
                        .HasColumnType("text");

                    b.HasKey("Ftk_id");

                    b.ToTable("Config_file_third_kind", (string)null);

                    b.HasData(
                        new
                        {
                            Ftkid = 1,
                            Firstkindid = "01",
                            Firstkindname = "集团",
                            Secondkindid = "01",
                            Secondkindname = "软件公司",
                            Thirdkindid = "02",
                            Thirdkindisretail = "否",
                            Thirdkindname = "外包组",
                            Thirdkindsaleid = "1"
                        });
                });

            modelBuilder.Entity("Domain.Entity.Config.Config_major", b =>
                {
                    b.Property<int>("Mak_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mak_id"));

                    b.Property<string>("Major_id")
                        .HasMaxLength(2)
                        .HasColumnType("char()");

                    b.Property<string>("Major_kind_id")
                        .HasMaxLength(2)
                        .HasColumnType("char()");

                    b.Property<string>("Major_kind_name")
                        .HasMaxLength(60)
                        .HasColumnType("varchar()");

                    b.Property<string>("Major_name")
                        .HasMaxLength(60)
                        .HasColumnType("varchar()");

                    b.Property<int?>("Test_amount")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.HasKey("Mak_id");

                    b.ToTable("Config_major", (string)null);

                    b.HasData(
                        new
                        {
                            Makid = 1,
                            Majorid = "01",
                            Majorkindid = "01",
                            Majorkindname = "销售",
                            Majorname = "人事经理",
                            Testamount = 0
                        });
                });

            modelBuilder.Entity("Domain.Entity.Config.Config_major_kind", b =>
                {
                    b.Property<int>("Mfk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mfk_id"));

                    b.Property<string>("Major_kind_id")
                        .HasMaxLength(2)
                        .HasColumnType("char()");

                    b.Property<string>("Major_kind_name")
                        .HasMaxLength(60)
                        .HasColumnType("varchar()");

                    b.HasKey("Mfk_id");

                    b.ToTable("Config_major_kind", (string)null);

                    b.HasData(
                        new
                        {
                            Mfkid = 1,
                            Majorkindid = "01",
                            Majorkindname = "销售"
                        });
                });

            modelBuilder.Entity("Domain.Entity.Config.Config_primary_key", b =>
                {
                    b.Property<int>("Prk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Prk_id"));

                    b.Property<string>("Key_name")
                        .HasMaxLength(60)
                        .HasColumnType("varchar()");

                    b.Property<string>("Primary_key")
                        .HasMaxLength(60)
                        .HasColumnType("varchar()");

                    b.Property<int>("Primary_key_status")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<string>("Primary_key_table")
                        .HasMaxLength(60)
                        .HasColumnType("varchar()");

                    b.HasKey("Prk_id");

                    b.ToTable("Config_primary_key", (string)null);

                    b.HasData(
                        new
                        {
                            Prkid = 1,
                            Keyname = "I级机构名称",
                            Primarykey = "firstKindName",
                            Primarykeystatus = 1,
                            Primarykeytable = "HumanFile"
                        });
                });

            modelBuilder.Entity("Domain.Entity.Config.Config_public_char", b =>
                {
                    b.Property<int>("Pbc_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pbc_id"));

                    b.Property<string>("Attribute_kind")
                        .HasMaxLength(60)
                        .HasColumnType("varchar()");

                    b.Property<string>("Attribute_name")
                        .HasMaxLength(60)
                        .HasColumnType("varchar()");

                    b.HasKey("Pbc_id");

                    b.ToTable("Config_public_char", (string)null);

                    b.HasData(
                        new
                        {
                            Pbcid = 1,
                            Attributekind = "国籍",
                            Attributename = "中国"
                        });
                });

            modelBuilder.Entity("Domain.Entity.Engage.Engage_interview", b =>
                {
                    b.Property<int>("Ein_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ein_id"));

                    b.Property<string>("Check_comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Check_status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Checker")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("EQ_degree")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Foreign_language_degree")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Human_major_id")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Human_major_kind_id")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Human_major_kind_name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Human_major_name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Human_name")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("IQ_degree")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Image_degree")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Interview_amount")
                        .HasColumnType("int");

                    b.Property<string>("Interview_comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Interview_status")
                        .HasColumnType("int");

                    b.Property<string>("Multi_quality_degree")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Native_language_degree")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("Registe_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Register")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Response_speed_degree")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Result")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Resume_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ein_id");

                    b.ToTable("Engage_interview", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Engage.Engage_resume", b =>
                {
                    b.Property<int>("Res_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Res_id"));

                    b.Property<string>("Attachment_name")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("Check_status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Checker")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal?>("Demand_salary_standard")
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("Engage_type")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Human_address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Human_age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Human_birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Human_birthplace")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Human_college")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Human_educated_degree")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Human_educated_major")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("Human_educated_years")
                        .HasColumnType("int");

                    b.Property<string>("Human_email")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Human_history_records")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_hobby")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Human_homephone")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Human_idcard")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Human_major_id")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Human_major_kind_id")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Human_major_kind_name")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Human_major_name")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Human_mobilephone")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Human_name")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Human_nationality")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Human_party")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Human_picture")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Human_postcode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Human_race")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Human_religion")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Human_sex")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Human_specility")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Human_telephone")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("Interview_status")
                        .HasColumnType("int");

                    b.Property<string>("Pass_checkComment")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("Pass_check_status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Pass_check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pass_checker")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Pass_passComment")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("Pass_regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pass_register")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Recomandation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Register")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Test_amount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Test_check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Test_checker")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("Total_points")
                        .HasColumnType("int");

                    b.HasKey("Res_id");

                    b.ToTable("Engage_resume", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Human_Resources_File.Engage_major_release", b =>
                {
                    b.Property<int>("Mre_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mre_id"));

                    b.Property<DateTime?>("ChangeTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Changer")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Engage_required")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Engage_type")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("First_kind_id")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("First_kind_name")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("Human_amount")
                        .HasColumnType("int");

                    b.Property<string>("Major_describe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_id")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Major_kind_id")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Major_kind_name")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Major_name")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("RegistTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Register")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Second_kind_id")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Second_kind_name")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Third_kind_id")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Third_kind_name")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("deadline")
                        .HasColumnType("datetime2");

                    b.HasKey("Mre_id");

                    b.ToTable("Engage_major_release", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.User.Users", b =>
                {
                    b.Property<int>("UId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UId"));

                    b.Property<string>("UName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar()");

                    b.Property<string>("UPassWord")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar()");

                    b.Property<string>("UTrueName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar()");

                    b.HasKey("UId");

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
